import Head from 'next/head'
import Image from 'next/image'
import Homepage from '../components/home/Homepage'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      
        <Head>
          <title>Techofic</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Homepage />
      
    </div>
  );
}
